"""Compile sourced finite uranium allocations; never manufacture unknown reserves."""
from pathlib import Path
import argparse
import hashlib
import json

ROOT = Path(__file__).resolve().parents[2]


def compile_seed(data):
    lines = [
        '# Generated by tools/data/build_uranium_seed.py; edit the sourced JSON.',
        '# Native integer flow is 100 kg U/week. Capacity is tU/week; reserves are kg U.',
        '# Country totals are game allocations across documented geological districts.',
        '# Unknown budgets and impassable Greenland are deliberately not invented.',
        'eon_uranium_seed_world = {',
    ]
    seen = set()
    for country in data['countries']:
        for site in country.get('game_seed_allocations', []):
            state = site['state_id']
            assert state not in seen, ('duplicate state allocation', state)
            seen.add(state)
            reserve = site['reserve_tu'] * 1000
            flow = site['initial_weekly_tu']
            ceiling = site['max_weekly_tu']
            assert reserve > 0 and 0 <= flow <= ceiling
            lines.extend([
                f" # {country['tag']}: state {state}; allocation, not measured local reserve.",
                f' {state} = {{',
                f'  set_variable = {{ eon_uranium_reserve_kg = {reserve:.3f} }}',
                f'  set_variable = {{ eon_uranium_capacity = {flow:.6f} }}',
                f'  set_variable = {{ eon_uranium_capacity_limit = {ceiling:.6f} }}',
                '  set_variable = { eon_uranium_applied_output = 0 }',
                '  eon_uranium_refresh_mine = yes',
                ' }',
            ])
    lines.append('}')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = ROOT / 'tools/data/uranium_2000.json'
    target = ROOT / 'common/scripted_effects/eon_uranium_seed_effects.txt'
    encoded = compile_seed(json.loads(source.read_text(encoding='utf-8-sig'))).encode('utf-8')
    if args.check:
        assert target.read_bytes() == encoded, 'generated seed differs from the source data'
    else:
        target.write_bytes(encoded)
    print(json.dumps({'seed_sha256': hashlib.sha256(encoded).hexdigest(), 'check': args.check}))


if __name__ == '__main__':
    main()
