"""Render the initial no-GoT missile history from existing 2000 source grants.

Only direct technology grants in the initial 2000.1.1 snapshot's GoT condition
are projected onto existing compatible non-GoT technologies. Later dated
snapshots, nuclear/ballistic missiles and stockpiles are deliberately excluded.
"""
from pathlib import Path
import hashlib
import json
import re

from test_research import ROOT, ast, get

DESTINATION = 'common/scripted_effects/eon_missile_non_got_history_effects.txt'
ACTION = 'common/on_actions/eon_missile_non_got_history_on_actions.txt'
FLAG = 'eon_missile_non_got_history_initialized'
EFFECT = 'eon_missile_non_got_history_initialize'
MAPPED = re.compile(r'(GLCM[1-8]?|cruise_missile|TEL_launched_missiles|TEL_[3-7]|air_defense|SAM[0-2]?)')


def records(root=ROOT):
    available = {key for key, _, nodes in ast(
        (root / 'common/technologies/non_got_missiles.txt').read_text(encoding='utf-8-sig'))
                 if key == 'technologies' for key, _, value in nodes if isinstance(value, list)}
    rows = []
    for path in sorted((root / 'history/countries').glob('*.txt')):
        raw = path.read_bytes()
        initial = get(ast(raw.decode('utf-8-sig')), '2000.1.1', [])
        mapped, hidden, launchers = {}, {}, None
        for key, _, nodes in initial:
            if key != 'if' or not isinstance(nodes, list):
                continue
            limit = get(nodes, 'limit', [])
            # Do not erase extra political, dated or country conditions.
            if limit != [('has_dlc', '=', 'Gotterdammerung')]:
                continue
            for field, _, value in nodes:
                if field == 'set_technology':
                    for tech, op, grant in value:
                        if op == '=' and grant == '1' and MAPPED.fullmatch(tech):
                            alias = tech + '_non_got'
                            assert alias in available, alias
                            mapped[alias] = 1
                        elif op == '=' and grant == '1' and re.fullmatch(r'hid_tech_missile_[1-9][0-9]*', tech):
                            hidden[tech] = 1
                elif field == 'set_variable':
                    for name, _, amount in value:
                        if name == 'num_launchers_set':
                            assert launchers is None, path
                            launchers = int(amount)
        if not mapped:
            continue
        has_glcm = 'GLCM_non_got' in mapped
        if has_glcm:
            # GLCM has the same first-node prerequisite in both visible folders.
            mapped['cruise_missile_non_got'] = 1
        else:
            # A country with only air defence receives no missile-launch sites.
            hidden, launchers = {}, None
        if launchers is None and hidden:
            # Sweden has only a hidden level in upstream history. Preserve its
            # actual cap as the callback counter rather than inventing a level.
            launchers = max(int(key.rsplit('_', 1)[1]) for key in hidden)
        rows.append(dict(tag=path.name.split(' - ', 1)[0],
                         source=path.relative_to(root).as_posix(),
                         sha256=hashlib.sha256(raw).hexdigest(),
                         techs=sorted(mapped), hidden=sorted(hidden, key=lambda key: int(key.rsplit('_', 1)[1])),
                         launchers=launchers))
    return rows


def render(rows=None):
    rows = records() if rows is None else rows
    lines = [
        '# Generated by tools/validation/missile_system/generate_non_got_history.py.',
        '# Source-owned 2000 grants only; no new historical research levels or stockpiles.',
        '# Nuclear and ballistic systems remain GoT-only. Existing national policies are unchanged.',
        f'{EFFECT} = {{',
        '\tif = {',
        '\t\tlimit = {',
        '\t\t\tNOT = { has_dlc = "Gotterdammerung" }',
        '\t\t\tdate < 2000.1.2',
        '\t\t}',
    ]
    for row in rows:
        lines.extend([
            f'\t\t# {row["source"]}',
            f'\t\t# SHA256: {row["sha256"]}',
            '\t\tif = {',
            f'\t\t\tlimit = {{ tag = {row["tag"]} }}',
            '\t\t\tif = {',
            '\t\t\t\tlimit = {',
            '\t\t\t\t\texists = yes',
            f'\t\t\t\t\tNOT = {{ has_country_flag = {FLAG} }}',
            '\t\t\t\t}',
            '\t\t\t\tset_technology = {',
            *[f'\t\t\t\t\t{tech} = 1' for tech in row['techs'] + row['hidden']],
            '\t\t\t\t\tpopup = no',
            '\t\t\t\t}',
            '\t\t\t\tcomplete_special_project = sp:sp_missile_project_non_got',
        ])
        if row['launchers'] is not None:
            lines.append(f'\t\t\t\tset_variable = {{ num_launchers_set = {row["launchers"]} }}')
        lines.extend([
            f'\t\t\t\tset_country_flag = {FLAG}',
            '\t\t\t}',
            '\t\t}',
        ])
    lines.extend(['\t}', '}'])
    return '\n'.join(lines) + '\n'


def action_text():
    # on_startup has NONE scope. Enter each country before calling a country
    # helper, so research callbacks keep the recipient as ROOT and THIS.
    return f'on_actions = {{\n\ton_startup = {{\n\t\teffect = {{\n\t\t\tevery_country = {{\n\t\t\t\t{EFFECT} = yes\n\t\t\t}}\n\t\t}}\n\t}}\n}}\n'


def write_game(path, text):
    # These are new script files, not localisation. Keeping them BOM-free also
    # prevents an interior BOM when native engines concatenate script buffers.
    (ROOT / path).write_bytes(text.replace('\n', '\r\n').encode('utf-8'))


if __name__ == '__main__':
    rows = records()
    write_game(DESTINATION, render(rows))
    write_game(ACTION, action_text())
    print(json.dumps(dict(countries=len(rows), countries_with_glcm=sum('GLCM_non_got' in row['techs'] for row in rows),
                         compatible_tech_grants=sum(len(row['techs']) for row in rows),
                         sources=rows), indent=2))
