title: "Era of Nations"
description: "Development documentation for Era of Nations, a standalone Hearts of Iron IV fork."
baseurl: ""
url: "" # No documentation website has been published.

markdown: kramdown
highlighter: rouge
theme: minima

collections:
  guides:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: "Home"
    url: "/"
  - title: "FAQ"
    url: "/faq"
  - title: "Support"
    url: "/technical-support"
  - title: "Tutorials"
    url: "/tutorials"
  - title: "Resources"
    url: "/team-resources"
  - title: "Changelogs"
    url: "/changelogs"
  - title: "Dev Diaries"
    url: "/dev-diaries-list"
  - title: "Country List"
    url: "/countries-list"
  - title: "Code Style Guide"
    url: "/dev-resources/code-stylization-guide"

social:
  - name: "GitHub"
    url: "https://github.com/Sany0ssse/Era-of-Nations"
